// error case: return value in void function

class Foo
{
    fun void foo()
    {
        // returning value from inside a void function
        return 5;
    }
}